name: Format CI


on:
  schedule:
    - cron: '0 12 * * *'
      branches: [ spotless ]
   

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2022-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      run: ./gradlew spotlessApply

    - name: Commit back to GitHub
      run: |
        git config --global user.name "github-actiuons[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit -m "Formatting..."
        git push -u origin spotless

    - name: Compile and run tests on robot code
      run: ./gradlew spotlessCheck
